#server:
#  port: 9000  #default port for tomcat 8080
#management:
#  port: 9001
logging:
  file: target/log.out

spring:main:
    web_environment: false   #
    show_banner: false       # not to print Spring message in the command line

debug: true